services:
  tiw-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiw
    ports:
      - "8080:8080"
    depends_on:
      - tiw-mysql
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/gruppidilavoro?serverTimezone=UTC
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      - app-network

  tiw-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gruppidilavoro
    ports:
      - "3306:3306"
    volumes:
      - tiw-mysql-data:/var/lib/mysql # persist the data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql  # Run the SQL script at initialization
      - ./tests/dbfiller.sql:/docker-entrypoint-initdb.d/dbfiller.sql  # Fill the DB with random data at initialization
      # while the db is active the scripts will not be run again
    networks:
      - app-network

volumes:
  tiw-mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
